In [1]:
import numpy as np

In [2]:
name = ["Alice", "Bob", "Cathy", "Doug"]
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [3]:
x = np.zeros(4, dtype = int)

In [5]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={"names" :("name", "age", "weight"),
                          "formats" :("U10", "i4", "f8")})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [6]:
data["name"] = name
data["age"] = age
data["weight"] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [7]:
# Get all names
data["name"]

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [8]:
# Get first row of data
data[0]

('Alice', 25, 55.)

In [9]:
# Get the name from the last row
data[-1]["name"]

'Doug'

In [14]:
# Get names where age is under 30
data[data["age"] < 30]["name"]

array(['Alice', 'Doug'], dtype='<U10')

# Creating Structured Arrays

In [15]:
np.dtype({"names" : ("name", "age", "weight"),
          "formats" : ("U10", "i4", "f8")})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [16]:
np.dtype({"names" : ("name", "age", "weight"),
          "formats" : ((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [17]:
np.dtype([("name", "S10"), ("age", "i4"), ("weight", "f8")])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [18]:
np.dtype("S10, i4, f8")

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

# More Advanced Compound Types

In [19]:
tp = np.dtype([("id", "i8"), ("mat", "f8", (3, 3))])
X = np.zeros(1, dtype = tp)
print(X[0])
print(X["mat"][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# RecordArrays: Structured Arrays with a Twist

In [20]:
data["age"]

array([25, 45, 37, 19])

In [21]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])

In [22]:
%timeit data["age"]
%timeit data_rec["age"]
%timeit data_rec.age

122 ns ± 3.5 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
2.17 µs ± 242 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
4.45 µs ± 494 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
